---
# tasks file for nova DB Setup

- name: DB sync for nova.
  shell: |
    nova-manage api_db sync
    nova-manage db sync
  become: yes
  become_user: "{{ nova_system_user_name }}"
  ignore_errors: True
  run_once: True
